### ISSUE TITLE
[feature request] using fclone backend to list drives

### ISSUE THREAD

**Issue by em108** [fxxkrlab/iCopy#9]
Hello and thank you so much for such a useful bot and been following closely on every single update.
I have a small feature to request though I don't know how hard it'll be to develop since I don't know that much of coding myself. 
It would be for one to be able to list all the shared drives using the fclone backend as buttons hence making it possible for one to easily choose a destination rather than the ID. It's a feature I saw in https://github.com/wrenfairbank/telegram_gcloner which was rather useful. Then one would be able to easily set their quick and copy folders on the go if they choose to. Context in the screenshot below.

It would make it easier to delete copy folders from favourites too. Unless there's an even easier option you had in mind which would also be great.

Thanks so much for the wonderful bot :)

![Screenshot_20200721-221041_Telegram](https://user-images.githubusercontent.com/35030185/88096268-0d346e80-cb9f-11ea-8bf8-b767f1034c8f.jpg)

**Comment by fxxkrlab** [comment]
This feature will be supported in future updates

But this is very inconvenient to choose destination folder for users who have a lot of team disks, or who have a lot of directories in the first level of the team directory.

In fact, we have discussed this topic in the TG group

**Comment by em108** [comment]
Thanks so much for the response. I very much love your work :)

**Comment by fxxkrlab** [comment]
Thank you very much for your concern about this project.
👍
